export const PlacesCategories = {
    "en":["Universities","Schools","Doctors","Hospitals","Drugstore","Banks","ATMs","Supermartet","Stores","Department stores","Commerce","Shops","Bars","Night clubs","Tourist attractions","Parks","Movie theaters","Restaurants","GYMs","Beauty salons","Clothing stores","Subway stations"],
    "es":["Universidades","Escuelas","Doctores","Hospitales","Farmacias","Bancos","Cajeros","Supermercados","Tiendas","Tiendas Departamentales","Comercios","Tiendas","Bares","Clubes Nocturnos","Atracciones Turísticas","Parques","Cines","Restaurantes","Gimnasios","Salones de Belleza","Tiendas de Ropa","Estaciones de transporte"],
    "fr":["Universités","Écoles","Médecins","Hôpitaux","Pharmacie","Banques","Caissiers","Supermarchés","Magasins","Boutiques départementales","Magasins","Magasins","pubs","Les boites de nuit","Attractions touristiques","Parcs","Cinémas","Restaurants","Gymnases","Salons de beauté","Magasins de vêtements","Stations de transport"],
    "de":["Universitäten","Schulen","Ärzte","Krankenhäuser","Apotheke","Banken","Kassierer","Supermärkte","Shops","Warenhäuser","Geschäfte","Shops","Pubs","Nachtclubs","Sehenswürdigkeiten","Parks","Kinos","Restaurants","Turnhallen","Schönheitssalons","Kleidungsgeschäft","Transportstationen"],
    "it":["Università","Scuole","Medici","Ospedali","Farmacia","Banche","Cassieri","Supermercati","I negozi","grandi magazzini","Negozi","I negozi","pub","Locali notturni","Cose da vedere","Parks","Cinema","Ristoranti","Palestre","Saloni di bellezza","Negozi di vestiti","Stazioni di trasporto"],
    "pt":["Universidades","Escolas","Doutores","Hospitais","Farmacia","Bancos","Caixas","Supermercados","Lojas","Lojas de departamentos","Lojas","Lojas","pubs","Casas noturnas","Atrações turísticas","Parques","Cinemas","Restaurantes","Ginásios","Salões de beleza","Lojas de roupa","Estações de transporte"],
    "ee":["Ülikoolid","Koolid","Arstid","Haiglad","Apteek","Pangad","Kassapidajad","Supermarketid","Kauplused","Kaubamajad","Poed","Kauplused","pubid","Ööklubid","Vaatamisväärsused","Pargid","Kinod","Restoranid","Spordisaalid","Ilusalongid","Riidepoed","Transpordijaamad"],
    "NIX":["university","schools","doctor","hospitals","drugstore","bank","atm","supermartet","stores","department_store","commerce","shops","bar","night_club","tourist_attraction","parks","movie_theater","restaurants","gym","beauty_salon","clothing_store","subway_statio"],
}